services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  minio:
    image: 'minio/minio:latest'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /data
    command: >
      minio server /data --console-address ":9001"


